config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'cards/show'
  get 'shops', to: 'shops#index'
  get 'infos', to: 'infos#index'
  resources :products
  resources :shops, only: [:index, :show] 
  resources :order_items
  resource :cards, only: [:show]
  resources :charges

  
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_subtotal



def subtotal
    order_items.collect{|order_item| order_item.valid? ? order_item.unit_price*order_item.quantity : 0}.sum
end


private
def set_subtotal
    self [:subtotal] = subtotal
end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
    belongs_to :order
    belongs_to :product

    before_save :set_unit_price
    before_save :set_total

def unit_price
    if persisted?
        self[:unit_price]
    else
        product.price
    end
end

def total
    unit_price * quantity
end

private

def set_unit_price
    self[:unit_price] = unit_price
end

def set_total
    self[:total] = total * quantity
end

end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_items
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
    include ApplicationHelper
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @order_items = current_order.order_items 
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
    end

    def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

    rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        
    end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

    def index
        
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

    def create
        @order = current_order
        @order_item = @order.order_items.new(order_params)
        @order.save
        session[:order_id] = @order.id
    end

    def update
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.update(order_params)
        @order_items = current_order.order_items
    end

    def destroy
        @order = current_order
        @order_item = @order.order_items.find(params[:id])
        @order_item.destroy
        @order_items = current_order.order_items
    end

    private
    def order_params
        params.require(:order_item).permit(:product_id, :quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  
  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :price, :image)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!
  def index
    @products = Product.all
    
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper




def current_order
    
    if !session[:order_id].nil?
        Order.find(session[:order_id]) 
    else
      Order.new  
    end
end


end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/cards/_card.html.erb
<%= link_to " #{current_order.order_items.size} produits d'une valeur de #{current_order.subtotal}$", cards_path %>

app/views/cards/_cards_item.html.erb
 <h1>Votre panier:</h1>

<% @order_items.each do |item|  %>

    <h3><%= item.product.title %></h3>
    <h5><%= item.product.price %></h5>



    <%= form_for item, remote: true do |f| %>

        <%= f.hidden_field :product_id, :value => item.product.id %>
        <%= f.number_field :quantity, :value => item.quantity.to_i %>
        <%= f.submit " Update card " %>

    <%=  link_to "Remove items", order_item_path(item), method: :delete, remote: true %> 

    <% end %>
    <h2>Subtotal:<%= item.total %></h2>

<% end %> 


<h2>La somme total des produits est : <%= current_order.subtotal %></h2>

app/views/cards/show.html.erb
<div id="card-item">
<%= render 'cards_item'%>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="A month's subscription" data-amount="500" data-locale="auto"></script>
<% end %>

app/views/infos/index.html.erb
<p>les informations nous concernant sont ci-dessous!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/create.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
<%# alert ('Produit ajouté au panier!') %>

app/views/order_items/destroy.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item'))%>")

app/views/order_items/update.js.erb
$('#card').html("<%= escape_javascript(render('cards/card'))%>")
$('#card-item').html("<%= escape_javascript(render('cards/cards_item'))%>")

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <% if product.image.attached?  %>
       <%= image_tag product.image, style: "width: 200px, display :block" %>
    <% end %>
    
    
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>
<p>
  <strong>image:</strong>
  <%= image_tag @product.image, style: "width: 200px, display :block" %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">La ferme du Boeny</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to 'Products' , shops_path, class:'nav-link'  %>
        </li>

         <li class="nav-item">
        <%= link_to 'infos' , infos_path, class:'nav-link'  %>
        </li>
         </ul>


      <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to 'Sign out' , destroy_user_session_path, method: :delete, class:'nav-link'  %>
        </li>
      <% else %>
        <li class="nav-item">
        <%= link_to 'register' , new_user_registration_path, class:'nav-link'  %>   
        </li>
        <li class="nav-item">
           <%= link_to 'Sign in' , new_user_session_path, class:'nav-link' %>
        </li>
      <% end %>
        
       
      </ul>
    </div>
  </div>
</nav>

app/views/shops/index.html.erb
<h1>Bienvenue</h1>
<p>Choisissez vos produits ici </p>
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<%# <#div class="card" style="width: 18rem;"> %>
  <%# <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">An item</li>
    <li class="list-group-item">A second item</li>
    <li class="list-group-item">A third item</li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</#div> %>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr> 

        <td><%= product.title %></td>
        <td><%= product.price %></td>
        
        <td><%= link_to 'Details', shop_path(product) %></td>

        <td>
        <%= form_for @order_item, remote: true do |f| %>
       
        <%= f.hidden_field :product_id, :value => product.id %>
        <%= f.number_field :quantity, :value => 1, :min => 1 %>
        <%= f.submit "Ajouter au panier" %>
         <% end %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="card">
 <%= render 'cards/card'%>
</div>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <strong></strong>
  <%= @product.title %>
</h1>
<p>
<strong>Descriptions:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Prix:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Back', root_path %>